// !!this is a list of things that i should be completing in stacks
// !!before moving on to solving striver's sheet and gfg questions

//?? the list of questions includes:
//?? 1. sorting a stack
//?? 2. creating two stacks in an array
//?? 3. creating a queue using two stacks
//?? 4. creating a stack using two queues
// ??CLASS 3 AND 4  INCLUDING THAT HISTOGRAM QUESTION WHICH INCLUDES
// ??LOGIC OF NEXT SMALLER ELEMENT OR PREVIOUS GREATER ELEMENT !!THIS TYPE
// ?? POSTFIX INFIX AND PREFIX
//?? 5. HOMEWORK QUESTIONS OF CODE HELP

// !!STRIVERS SHEET
// !!GFG QUESTIONS

// !!ON COMPLETING EVERYTHING THEN WE CAN MOVE TOWARDS HARDCORE LEETCODING FOR INTERVIEW PREPARATION

// !!INTERVIEW PREPARATION WILL NOT ONLY INCLUDE PROBLEM SOLVING BUT
// !!EXPLAINING IN TERMS OF TIME AND SPACE COMPLEXITY AND

// !!ALSO I NEED TO BE READ MORE AND MORE GFG AND MEDIUM ARTICLES TO GO IN DEPTH

// !! AND MOST IMPORTANTLY LEARN FROM OTHERS SOLUTION FROM LEETCODE WHEN WE WILL BE LEETCODING
// !!OR FOR A MATTER OF FACT ANYWHERE I WILL BE DOING THESE CODING QUESTIONS !!